multiplesbd/apps/BaseDatos/urls.py
from django.conf.urls import url

from .views import BaseDatosListView


app_name = 'Bases de Datos'

urlpatterns = [
    url(r'^$', BaseDatosListView.as_view(), name='basedatos-listar'),
]

multiplesbd/apps/Periodistas/urls.py
from django.conf.urls import url

from .views import PeriodistasListView

app_name = 'Periodistas'

urlpatterns = [
    url(r'^$', PeriodistasListView.as_view(), name='periodistas-listar'),
]

multiplesbd/apps/Usuarios/urls.py
from django.conf.urls import url
from .views import LoginView, LogoutView

urlpatterns = [
    url(r'^login', LoginView.as_view(), name='usuario-login'),
    url(r'^logout', LogoutView.as_view(),  name='usuario-logout'),
]

multiplesbd/multiplesbd/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from apps.Usuarios.views import LoginView, LogoutView
from apps.BaseDatos.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basedatos/', include('apps.BaseDatos.urls', namespace='BaseDatos')),
    url(r'^usuario/', include('apps.Usuarios.urls', namespace='Usuarios')),
    url(r'^periodistas/', include('apps.Periodistas.urls', namespace='Periodistas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multiplesbd/apps/BaseDatos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class BaseDatos(models.Model):
    BDNombre = models.CharField(max_length=255, verbose_name="Nombre")
    BDDescripcion = models.CharField(max_length=100, null=True, blank=True, verbose_name="Descripción")

    def __str__(self):
        return self.BDNombre

multiplesbd/apps/Periodistas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Periodista(models.Model):
    PIdentificacion = models.CharField(max_length=20, verbose_name="No. de Identificación")
    PPrimerNombre = models.CharField(max_length=50, verbose_name="Primer Nombre")
    PSegundoNombre = models.CharField(max_length=50, null=True, blank=True, verbose_name="Segundo Nombre")
    PPrimerApellido = models.CharField(max_length=50, verbose_name="Primer Apellido")
    PSegundoApellido = models.CharField(max_length=50, null=True, blank=True, verbose_name="Segundo Apellido")
    PEmail = models.EmailField(verbose_name="Correo Electronico")
    PTelefono = models.CharField(max_length=255, null=True, blank=True, verbose_name="Telefono")
    PCelular = models.CharField(max_length=20, null=True, blank=True, verbose_name="Celular")
    PEmpresa = models.CharField(max_length=255, null=True, blank=True, verbose_name="Empresa")
    PFacebook = models.URLField(null=True, blank=True, verbose_name="Facebook")
    PTwitter = models.URLField(null=True, blank=True, verbose_name="Twitter")
    PCargo = models.CharField(max_length=150, null=True, blank=True, verbose_name="Cargo")
    POrganizacion = models.CharField(max_length=255, null=True, blank=True, verbose_name="Organización")

    class Meta:
        app_label = 'Periodistas'

    def __str__(self):
        return self.PPrimerNombre

multiplesbd/apps/Usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

multiplesbd/apps/BaseDatos/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import BaseDatos

queryset = BaseDatos.objects.all()
CHOICES_BASEDATOS = [(q.BDNombre, q.BDNombre) for q in queryset]

class BaseDatosForm(forms.ModelForm):

    class Meta:
        model = BaseDatos

        fields = [
            'BDNombre',
            'BDDescripcion'
        ]

        labels = {
            'BDNombre': 'Seleccione la base de datos:',
            'BDDescripcion': 'Descripción'
        }

        help_texts = {
            'BDNombre': 'Nombre de la base de datos',
        }

        widgets = {
            'BDNombre': forms.Select(choices=CHOICES_BASEDATOS),
            'BDDescripcion': forms.TextInput()
        }

multiplesbd/apps/BaseDatos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.views.generic import FormView
from .models import BaseDatos
from .forms import BaseDatosForm


def index(request):
    return render(request, "index.html", {})


class BaseDatosListView(FormView):
    template_name = 'BaseDatos/BDListar.html'
    form_class = BaseDatosForm
    success_url = 'BaseDatos:basedatos-listar'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BaseDatosListView, self).dispatch( *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = BaseDatosForm(request.POST)
            if form.is_valid():
                q = form.cleaned_data['BDNombre']
                return HttpResponseRedirect("/%s" % q)
        form = BaseDatosForm()
        return render(request, self.get_template_names(), { 'form': form })

multiplesbd/apps/Periodistas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from .models import Periodista


class PeriodistasListView(ListView):
    model = Periodista
    template_name = 'Periodistas/PListar.html'
    context_object_name = "periodistas"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PeriodistasListView, self).dispatch( *args, **kwargs)

multiplesbd/apps/Usuarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import FormView, RedirectView


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = "Usuario/ULogin.html"
    success_url =  reverse_lazy("BaseDatos:basedatos-listar")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)


class LogoutView(RedirectView):
    pattern_name = 'Usuarios:usuario-login'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            logout(self.request)
        return super(LogoutView, self).get_redirect_url(*args, **kwargs)

multiplesbd/apps/templates/BaseDatos/BDListar.html
{% extends "../master.html" %}

{% block content %}
<div class="container" style="margin-top:60px">

  {% if form %}
  <h1>Bases de datos</h1>

  <div class="row">
    <div class="col">
      <form class="form-inline" method="POST" >
        {% csrf_token %}
        <div class="form-group">
          <label for="basedatos">Seleccione una base de datos:</label>
          <select id="{{form.BDNombre.name}}" name="{{form.BDNombre.name}}" class="form-control">
            <option value="">-- Seleccione --</option>
            {% for option in form.BDNombre %}
            <option value="{{option.choice_label|lower}}">{{option.choice_label}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Continuar</button>
        </div>
      </form>
    </div>
  </div>
  {% else %}
  <div class="alert alert-info">
    <strong>Información!</strong> No se encontrarón bases de datos para listar.
  </div>
  {% endif %}
</div>
{% endblock %}

multiplesbd/apps/templates/Periodistas/PListar.html
{% extends "../master.html" %}

{% block content %}
<div class="container" style="margin-top:60px">
  <h1>Periodistas</h1>

  {% if periodistas %}
  
  {% else %}
  <div class="alert alert-info">
    <strong>Información!</strong> No se encontrarón datos.
  </div>
  {% endif %}
</div>
{% endblock %}

multiplesbd/apps/templates/Usuario/ULogin.html
{% extends "../master.html" %}

{% block style %}
<style type="text/css">
body {
  background: #eee !important;
}
</style>
{% endblock %}

{% block navbar %}

{% endblock %}

{% block content %}
<div class="wrapper">
   <form class="form-signin" method="POST">
     {% csrf_token %}

     <div class="form-group text-center">
      <h2 class="form-signin-heading">Ingreso a la aplicación</h2>
     </div>

     <div class="form-group">
      <input type="text" class="form-control" name="username" placeholder="Nombre de Usuario" required="" autofocus="" />
     </div>

     <div class="form-group">
      <input type="password" class="form-control" name="password" placeholder="Contraseña" required=""/>
     </div>

     <div class="form-group">
      <button class="btn btn-md btn-primary btn-block" type="submit">Ingresar</button>
     </div>

     <div class="form-group text-center">
      <a href="{% url 'index' %}" class="btn btn-md btn-primary btn-block" role="button">Regresar</a>
     </div>

   </form>
 </div>
{% endblock %}

multiplesbd/apps/templates/index.html
{% extends "master.html" %}

{% load staticfiles %}

{% block style %}
<style type="text/css" scoped>
  .col-centrada{
    float: none;
    margin: 0 auto;
    padding: 20px;
    text-align: center;
  }

  .marginTop {
    margin-bottom: 20px;
  }

  .marginTop img {
    border-radius: 100%;
  }

  .marginTop img:hover {
    transform: rotate(360deg);
    box-shadow: 0px 3px 10px #808080;
    transition: all ease 2s;
  }

  a#btn:hover {
    box-shadow: 0px 3px 10px #808080;
  }
</style>
{% endblock %}

{% block content %}
<div class="container" style="margin-top:60px">
  <div class="col-lg-6 col-centrada">
    <div class="marginTop">
      <img src="{% static "img/logos/logo.png" %}" />
    </div>
    <div class="marginTop">
      <a id="btn" href="{% url 'Usuarios:usuario-login' %}" class="btn btn-info btn-md" role="button">Iniciar sesión</a>
    </div>
  </div>
</div>
{% endblock %}

multiplesbd/apps/templates/master.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-2.2.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    {% block style %}
    {% endblock %}
  </head>
  <body>
    {% block navbar %}
      {% if user.is_authenticated %}
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- El logotipo y el icono que despliega el menú se agrupan
         para mostrarlos mejor en los dispositivos móviles -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Desplegar navegación</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Bienvenido</a>
        </div>

        <!-- Agrupar los enlaces de navegación, los formularios y cualquier
             otro elemento que se pueda ocultar al minimizar la barra -->
        <div class="collapse navbar-collapse navbar-ex1-collapse navbar-right" style="margin-right:4px">
          <ul class="nav navbar-nav mr-2">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {{request.user.get_username}}
              <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                {% if request.user.is_staff%}
                  <li><a href="{% url 'admin:index' %}">Administrador</a></li>
                {% endif %}
                <li class="divider"></li>
                <li><a href="{% url 'Usuarios:usuario-logout' %}">Cerrar sesión</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
      {% endif %}
    {% endblock %}

    {% block content %}

    {% endblock %}
  </body>
</html>